export const testimonials = [
  {
    name: "Priya",
    location: "India to France",
    comment: "Got my Schengen visa using their combo pack — flawless!",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/women/75.jpg",
  },
  {
    name: "Ahmed",
    location: "Dubai to London",
    comment:
      "Their hotel docs passed VFS screening for my UK visa. Super fast!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    name: "John",
    location: "India to Canada",
    comment: "I didn’t know how to begin, but they made it super easy!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
  },
  {
    name: "Li Wei",
    location: "China to Italy",
    comment: "Documents were accepted without any issues. Highly recommend!",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    name: "Maria",
    location: "Brazil to Germany",
    comment: "Their support team helped me through every step. Thank you!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
  },
  {
    name: "Omar",
    location: "Egypt to Spain",
    comment: "Very professional and quick service. Got my visa smoothly.",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
  },
  {
    name: "Sofia",
    location: "Argentina to Portugal",
    comment: "Everything was handled perfectly. Stress-free process!",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    name: "Raj",
    location: "India to USA",
    comment: "Got my flight itinerary and hotel docs within hours. Perfect!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
  },
  {
    name: "Yuki",
    location: "Japan to France",
    comment: "Easy to use and totally worth the price!",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    name: "Noah",
    location: "USA to Switzerland",
    comment: "Their PDF documents look very professional. Visa approved!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
  },
  {
    name: "Fatima",
    location: "UAE to Greece",
    comment: "Customer service was responsive and helpful. Loved it!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    name: "Lucas",
    location: "Mexico to Netherlands",
    comment: "Everything matched what the embassy required.",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    name: "Mei",
    location: "Singapore to Austria",
    comment: "Highly trusted service. Will use again for sure.",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    name: "Daniel",
    location: "South Africa to Belgium",
    comment: "Efficient and accurate documentation!",
    rating: 5,
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
  },
  {
    name: "Anika",
    location: "Bangladesh to Sweden",
    comment: "Visa came through thanks to their neat documents.",
    rating: 4,
    avatar: "https://randomuser.me/api/portraits/women/39.jpg",
  },
];
